# ~/.config/sway/conf.d/35-idle.conf
# 配置节电休眠
# 超时时间在脚本中配置：~/.config/sway/scripts/start-swayidle.sh

exec_always --no-startup-id ~/.config/sway/scripts/start-swayidle.sh
exec_always --no-startup-id ~/.config/sway/scripts/watch-power-state.sh
